#conf.version = 11

#mongo_urls = mongodb://root:O249MCkl.~laPeNe@10.2.0.216:30310/?directConnection=true
#mongo_urls = mongodb://root:O249MCkl.~laPeNe@10.42.0.96:27017,10.42.0.97:27017/?replicaSet=rs1
#mongo_urls = mongodb://root:O249MCkl.~laPeNe@127.0.0.1:27017/admin?directConnection=true
#mongo_urls = mongodb://msuser:MySafePassword123!@127.0.0.1:27018/admin?authSource=admin&directConnection=true
#tunnel.address = mongodb://root:b841Pt6cOrMppzmX@10.2.0.216:32255

#filter.namespace.black = config,local

#sync_mode = all


conf.version = 11
mongo_urls = 
tunnel.address= mongodb://root:YcYbhFKuCwso~CxL@10.2.0.216:30378
sync_mode = all
full_sync.executor.insert_on_dup_update = true

